name: Xcode UT on PR 

on:
  pull_request:
    types:
      - opened
    branches: 
      - main
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: macos-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v2 # Githubやサードパーティの公開アクションを利用
      
      # UTを実行
      - name: execute UT
        run: arch -x86_64 xcrun xcodebuild -project SampleApp/SampleApp.xcodeproj/
          -scheme SampleApp
          -destination "platform=iOS Simulator,name=iPhone 13,OS=latest"
          -skip-testing:SampleAppUITests
          -resultBundlePath TestResults 
          clean test -quiet

      # テスト結果を表示
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()